title: Michael M.
logo: "/images/farishah-bitmoji.jpg?raw=true" 
description: > 
  <br><br>
  Software Engineer @ Microsoft 
  <br><br>
  MS in Software Engineering @ UTD 
  <br><br>  
  <a href="https://mimuruth-msft.github.io/aboutme">About Me</a>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
